server.port=8080
logging.level.root=INFO
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.annotation-scanner.enabled=true

database.url=jdbc:postgresql://127.0.0.1:5432/servicerouterdb
database.username=postgres
database.password=

openai.api.key=REPLACE_ME
openai.metadata.model=gpt-4o-mini
openai.complaint.generation.model=gpt-4o-mini
openai.embedding.model=text-embedding-3-small
embedding.batch.size=1000
